import type { Metadata } from "next";

import "./globals.css";


import Providers from "~/providers/Provider";
import Sidebar from "~/components/sidebar/sidebar";
import localFont from "next/font/local";
import Footer from "~/components/Footer";
const NeueMontrealRegular=localFont(
    {
        src: '../fonts/NeueMontreal-Regular.woff2',
        variable: '--font-NeuMontrealRegular',

    }
)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${NeueMontrealRegular.variable}`}>
      <body className={'font-primary text-primary'} >
      <Providers>
      <Sidebar>

      {children}
      </Sidebar>
          <Footer/>
          </Providers>
      </body>
    </html>
  );
}
