import user_icon from './user.svg'
import dropDown_icon from './dropdown .png'
import arrow_right_icon from './arrow-right.svg'
import blurImg from './blur.jpg'
import like_outline_icon from './like_outline.png'
import like_fill from './like_fill.png'
import google_icon from './google_icon.svg'
import icon from './icon.svg'
import Logo from './logo.png'
import loginBg from './login-bg.png'
import Quote from './quote close.svg'
import Section1 from './section1-title.png'
import Stars from './stars.svg'
import PlusIcon from './Plus.svg'
import SaasBg from './saas-bg.svg'
import Bag from './bag_music.svg'
import Tune from './tune.svg'
import Logout from './Login 3.svg'
import DriveUpload from './drive_folder_upload.svg'
import Speak from './User Speak.svg'
import Companies from './companies.svg'
import Visual from './visual.svg'
import Speaker from './speaker.svg'
import BgSignin from './bg-signin.svg'
import LogoWhite from './Logo.svg'
import BgFaq from './bg-faq.svg'
import MenuOpen from './menu_open.svg'
export {LogoWhite,Speaker,PlusIcon, BgSignin, Bag,Tune,Logout,DriveUpload,Speak, MenuOpen,BgFaq,Stars,Quote,Visual,Companies,SaasBg,Section1,Logo,loginBg,user_icon,dropDown_icon,arrow_right_icon,blurImg,like_outline_icon,like_fill,google_icon,icon}
